version: 2.1

jobs:
  build-android:
    docker:
      - image: cimg/node:20.11-browsers-android
    working_directory: ~/project/android
    steps:
      - checkout:
          path: ~/project

      - run:
          name: Install Node.js dependencies
          command: |
            cd ~/project
            yarn install

      - run:
          name: Install Android SDK & Build Tools
          command: |
            yes | sdkmanager --sdk_root=$ANDROID_SDK_ROOT "platform-tools" "platforms;android-33" "build-tools;33.0.2" || true

      - run:
          name: Accept Android Licenses
          command: |
            yes | sdkmanager --licenses || true

      - run:
          name: Build Android Release APK
          command: ./gradlew assembleRelease --no-daemon --console=plain

      - store_artifacts:
          path: ~/project/android/app/build/outputs/apk/release
          destination: release-apk

workflows:
  build-and-deploy:
    jobs:
      - build-android
